root: true
parser: babel-eslint
env:
  node: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
rules:
  prettier/prettier: error
overrides:
  - files:
      - webpack.*.js
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
          peerDependencies: true
  - files:
      - src/**/*
    env:
      browser: true
      node: false
    settings:
      import/resolver:
        webpack:
          config: "webpack.common.js"
